Source/Dogwood.Web.Mvc/Models/Attribute/EnumsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Dogwood.Data.EntityClasses;
using Dogwood.Data.DatabaseSpecific;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.HelperClasses;

namespace Dogwood.Web.Mvc.Models.Attribute
{
    public class EnumsViewModel
    {
        public IEnumerable<AttributeEntity> Attributes { get; set; }

        public EnumsViewModel()
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                var attributes = new EntityCollection<AttributeEntity>();
                adapter.FetchEntityCollection(attributes, null);
                Attributes = attributes.OrderBy(m => m.Id).ToList();
            }            
        }
    }
}

Source/Dogwood.Web.Mvc/Models/AttributeMeta/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data.HelperClasses;
using Dogwood.Data.EntityClasses;

namespace Dogwood.Web.Mvc.Models.AttributeMeta
{
    public class CreateViewModel
    {
        public int SelectedAttributeId { get; set; }
        public SelectList AttributeSelectList { get; set; }
        public short SelectedDataTypeId { get; set; }
        public SelectList DataTypeSelectList { get; set; }
        public int ClassId { get; set; }
        public bool IsNullable { get; set; }
        public bool IsImmutable { get; set; }
        public byte[] DefaultValue { get; set; }

        public CreateViewModel()
        {

        }

        public CreateViewModel(int classId)
        {
            this.ClassId = classId;

            Dictionary<int, string> dataTypes = new Dictionary<int, string>();
            dataTypes.Add(1, "String");
            dataTypes.Add(2, "Int");
            dataTypes.Add(3, "Long");
            dataTypes.Add(4, "Bool");
            dataTypes.Add(6, "DateTime");
            DataTypeSelectList = new SelectList(dataTypes, "Key", "Value");

            using (IDataAccessAdapter adapter = new DataAccessAdapter())
            {
                // used string attributes via metadata
                EntityCollection<AttributeMetadataEntity> stringMetas = new EntityCollection<AttributeMetadataEntity>();
                IRelationPredicateBucket filterBucket = new RelationPredicateBucket();
                filterBucket.PredicateExpression.Add(AttributeMetadataFields.ClassId == classId);
                adapter.FetchEntityCollection(stringMetas, filterBucket);

                // all string attributes
                EntityCollection<AttributeEntity> stringAttributes = new EntityCollection<AttributeEntity>();
                adapter.FetchEntityCollection(stringAttributes, null);

                // select list of unused attributes
                this.AttributeSelectList = new SelectList(
                    stringAttributes.Where(m => !stringMetas.Select(n => n.AttributeId).Contains(m.Id))
                    .ToList(), "Id", "Value");
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Models/AttributeMeta/DeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data;
using Dogwood.Data.EntityClasses;

namespace Dogwood.Web.Mvc.Models.AttributeMeta
{
    public class DeleteViewModel
    {
        public int Id { get; set; }
        public string Attribute { get; set; }

        public DeleteViewModel()
        {

        }

        public DeleteViewModel(int id)
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter())
            {
                IPrefetchPath2 path = new PrefetchPath2(EntityType.AttributeMetadataEntity);
                path.Add(AttributeMetadataEntity.PrefetchPathAttribute);
                AttributeMetadataEntity meta = new AttributeMetadataEntity(id);
                adapter.FetchEntity(meta, path);
                Id = id;
                Attribute = meta.Attribute.Value;
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Models/AttributeMeta/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data;
using Dogwood.Data.EntityClasses;
using System.Web.Mvc;
using Dogwood.Data.HelperClasses;

namespace Dogwood.Web.Mvc.Models.AttributeMeta
{
    public class EditViewModel
    {
        public int Id { get; set; }
        public bool IsNullable { get; set; }
        public bool IsImmutable { get; set; }
        public int SelectedAttributeId { get; set; }
        public SelectList AttributeSelectList { get; set; }
        public byte[] DefaultValue { get; set; }
        public int SelectedDataTypeId { get; set; }
        public SelectList DataTypeSelectList { get; set; }

        public EditViewModel() { }

        public EditViewModel(int id)
        {
            Dictionary<int, string> dataTypes = new Dictionary<int, string>();
            dataTypes.Add(1, "String");
            dataTypes.Add(2, "Int");
            dataTypes.Add(3, "Long");
            dataTypes.Add(4, "Bool");
            dataTypes.Add(6, "DateTime");
            DataTypeSelectList = new SelectList(dataTypes, "Key", "Value");

            using (IDataAccessAdapter adapter = new DataAccessAdapter())
            {
                EntityCollection<AttributeEntity> attributes = new EntityCollection<AttributeEntity>();
                adapter.FetchEntityCollection(attributes, null);
                AttributeSelectList = new SelectList(attributes.OrderBy(m => m.Value), "Id", "Value");
                AttributeMetadataEntity meta = new AttributeMetadataEntity(id);
                adapter.FetchEntity(meta);
                Id = id;
                SelectedAttributeId = meta.AttributeId;
                SelectedDataTypeId = meta.DataTypeId;
                IsNullable = meta.IsNullable;
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Models/AttributeMeta/EnumsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Dogwood.Data.EntityClasses;
using Dogwood.Data.DatabaseSpecific;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.HelperClasses;
using Dogwood.Data;

namespace Dogwood.Web.Mvc.Models.AttributeMeta
{
    public class EnumsViewModel
    {
        public IEnumerable<RelationshipMetadataEntity> RelationshipMetadata { get; set; }
        public IEnumerable<AttributeMetadataEntity> AttributeMetadata { get; set; }

        public EnumsViewModel()
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                var path = new PrefetchPath2(EntityType.RelationshipMetadataEntity);
                path.Add(RelationshipMetadataEntity.PrefetchPathFkClass);
                path.Add(RelationshipMetadataEntity.PrefetchPathAttribute);

                var metadata = new EntityCollection<RelationshipMetadataEntity>();
                adapter.FetchEntityCollection(metadata, null, path);
                RelationshipMetadata = metadata.OrderBy(m => m.Id).ToList();

                var attributePath = new PrefetchPath2(EntityType.AttributeMetadataEntity);
                attributePath.Add(AttributeMetadataEntity.PrefetchPathClass);
                attributePath.Add(AttributeMetadataEntity.PrefetchPathAttribute);

                var attributeMeta = new EntityCollection<AttributeMetadataEntity>();
                adapter.FetchEntityCollection(attributeMeta, null, attributePath);
                AttributeMetadata = attributeMeta.OrderBy(m => m.Id).ToList();
            }            
        }
    }
}

Source/Dogwood.Web.Mvc/Models/Class/AllEntititesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Dogwood.Data.EntityClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data.HelperClasses;
using Dogwood.Data;
using Dogwood.Service;

namespace Dogwood.Web.Mvc.Models.Class
{
    public class AllEntitiesViewModel
    {
        public IList<EntityViewModel> AllClassTypes { get; set; }

        public AllEntitiesViewModel()
        {
            IClassService service = new ClassService();
            var allClasses = service.GetAll();
            AllClassTypes = new List<EntityViewModel>();
            ((List<ClassEntity>)allClasses.ToList()).ForEach(m => AllClassTypes.Add(new EntityViewModel()
            {
                Id = m.Id,
                Class = m
            }));
        }
    }
}

Source/Dogwood.Web.Mvc/Models/Class/ClassMetaViewModel.cs
using System.Collections.Generic;
using Dogwood.Data.EntityClasses;
using Dogwood.Service;

namespace Dogwood.Web.Mvc.Models.Class
{
    public class ClassMetaViewModel
    {
        public IEnumerable<ClassEntity> AllClasses { get; set; }

        public ClassMetaViewModel(IClassService service)
        {
            AllClasses = service.GetAll();
        }
    }
}

Source/Dogwood.Web.Mvc/Controllers/AttributeMetaController.cs
using System;
using System.Web.Mvc;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data.EntityClasses;
using Dogwood.Service;
using Dogwood.Web.Mvc.Models.AttributeMeta;

namespace Dogwood.Web.Mvc.Controllers
{
    public class AttributeMetaController : Controller
    {
        public ActionResult Create(int id)
        {
            CreateViewModel vm = new CreateViewModel(id);
            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(CreateViewModel vm)
        {
            IMetadataService service = new AttributeMetadataService();

            try
            {
                service.Create(vm.ClassId, vm.SelectedDataTypeId, vm.SelectedAttributeId, vm.IsNullable, vm.IsImmutable, vm.DefaultValue);
                return RedirectToAction("CloseWindow", "Home");
            }
            catch (Exception)
            {
                return Create(vm.ClassId);
            }
        }

        public ActionResult Edit(int id)
        {
            EditViewModel vm = new EditViewModel(id);
            return View(vm);
        }

        public PartialViewResult CreateSql(int id)
        {
            IMetadataService service = new AttributeMetadataService();
            var entity = service.Get(id);
            return PartialView(entity);
        }

        [HttpPost]
        public ActionResult Edit(EditViewModel vm)
        {
            IMetadataService service = new AttributeMetadataService();

            try
            {
                service.Update(vm.Id, vm.SelectedDataTypeId, vm.IsNullable, vm.IsImmutable, vm.DefaultValue);
                return RedirectToAction("CloseWindow", "Home");
            }
            catch (Exception)
            {
                return Edit(vm.Id);
                throw;
            }
        }

        public ActionResult Delete(int id)
        {
            DeleteViewModel vm = new DeleteViewModel(id);
            return View(vm);
        }

        [HttpPost]
        public ActionResult Delete(DeleteViewModel vm)
        {
            try
            {
                using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
                {
                    AttributeMetadataEntity meta = new AttributeMetadataEntity(vm.Id);

                    // attribute-value pairs should be cascade deleted by the database
                    adapter.DeleteEntity(meta);

                    return RedirectToAction("CloseWindow", "Home");
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult Enums()
        {
            var vm = new EnumsViewModel();
            return View(vm);
        }
    }
}

Source/Dogwood.Web.Mvc/Controllers/RelationshipMetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dogwood.Web.Mvc.Models.ForeignKeyMeta;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data.EntityClasses;
using System.Data;
using Dogwood.Data.HelperClasses;
using Dogwood.Data;
using Dogwood.Service;

namespace Dogwood.Web.Mvc.Controllers
{
    public class RelationshipMetaController : Controller
    {
        public ActionResult Create(int id)
        {
            CreateViewModel vm = new CreateViewModel(id);
            return View(vm);
        }

        public PartialViewResult CreateSql(int id)
        {
            IRelationshipMetadataService service = new RelationshipMetadataService();
            var entity = service.Get(id);
            return PartialView(entity);
        }

        [HttpPost]
        public ActionResult Create(CreateViewModel vm)
        {
            IRelationshipMetadataService service = new RelationshipMetadataService();

            try
            {
                RelationshipMetadataDto dto = new RelationshipMetadataDto()
                {
                    AttributeId = vm.ForeignKeyAttributeId,
                    ClassId = vm.ClassId,
                    PkClassId = vm.PkClassId,
                    IsNullable = vm.IsNullable,
                    DefaultValue = vm.DefaultValue,
                    OneToManyValue = vm.OneToManyValue,
                    BehaviorType = vm.SelectedBehaviorType,
                    CascadeDefaultValue = vm.CascadeDefaultValue
                };

                service.Create(dto);
                return RedirectToAction("CloseWindow", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }           
        }
     
        public ActionResult Edit(int id)
        {
            EditViewModel vm = new EditViewModel(id);
            return View(vm);
        }

        [HttpPost]
        public JsonResult OneToManyValueIsValid(string OneToManyValue, int PkClassId, int Id)
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                EntityCollection<RelationshipMetadataEntity> classesWithOtmValue = new EntityCollection<RelationshipMetadataEntity>();
                IRelationPredicateBucket filterBucket = new RelationPredicateBucket();
                filterBucket.PredicateExpression.Add(RelationshipMetadataFields.OneToManyValue == OneToManyValue);
                filterBucket.PredicateExpression.AddWithAnd(RelationshipMetadataFields.PkClassId == PkClassId);
                filterBucket.PredicateExpression.AddWithAnd(RelationshipMetadataFields.Id != Id);
                adapter.FetchEntityCollection(classesWithOtmValue, filterBucket);

                if (classesWithOtmValue.Count == 0)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("A relationship with that property name has already been created for this class", JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(EditViewModel vm)
        {
            IRelationshipMetadataService service = new RelationshipMetadataService();

            try
            {
                RelationshipMetadataDto dto = new RelationshipMetadataDto()
                {
                    Id = vm.Id,
                    IsNullable = vm.IsNullable,
                    ClassId = vm.ClassId,
                    PkClassId = vm.PkClassId,
                    DefaultValue = vm.DefaultValue,
                    OneToManyValue = vm.OneToManyValue,
                    BehaviorType = vm.SelectedBehaviorType,
                    CascadeDefaultValue = vm.CascadeDefaultValue
                };

                service.Update(dto);
                return RedirectToAction("CloseWindow", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }  
        }

        public ActionResult Delete(int id)
        {
            DeleteViewModel vm = new DeleteViewModel(id);
            return View(vm);
        }

        [HttpPost]
        public ActionResult Delete(DeleteViewModel vm)
        {
            try
            {
                using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
                {
                    RelationshipMetadataEntity meta = new RelationshipMetadataEntity(vm.Id);

                    // attribute-value pairs should be cascade deleted by the database
                    adapter.DeleteEntity(meta);

                    return RedirectToAction("CloseWindow", "Home");
                }
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Views/Class/AllEntities.cshtml
@model Dogwood.Web.Mvc.Models.Class.AllEntitiesViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@foreach (var item in Model.AllClassTypes)
{
    @Html.Partial("EntityCode", item)
    <br />
}

Source/Dogwood.Web.Mvc/Views/Class/AllPrefetches.cshtml
@model Dogwood.Web.Mvc.Models.Class.AllEntitiesViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="font-family: Consolas">
    @foreach (var item in Model.AllClassTypes)
    {
        <text>public partial class</text> @(item.Class.Name)<text>Entity</text>
        <br />
        <text>{</text>
        @Html.Partial("EntityPrefetchCode", item)
        <br />
        <text>}</text>
        <br />
        <br />
    }
</div>

Source/Dogwood.Web.Mvc/Views/Class/ClassMeta.cshtml
@model Dogwood.Web.Mvc.Models.Class.ClassMetaViewModel
@{
    ViewBag.Title = "ClassMeta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Dogwood Class Metadata</h2>
<table>
     <tr>
            <th colspan="3">
                &nbsp;
            </th>           
            <th style="text-align:right">
                Data Type
            </th>
            <th style="text-align:right">
                Is Nullable
            </th>
            <th style="text-align:right">
               Is Immutable
            </th>
        </tr>
    @foreach (var item in Model.AllClasses)
    {
    
        <tr class="classRow">
            <td class="alignRight">
                @Html.Encode(item.Id)
            </td>
            <td colspan="5">
                @Html.Encode(item.Name)
            </td>
        </tr>

        foreach (var meta in item.AttributeMetadata)
        {
            <tr>
                <td>
                    &nbsp;
                </td>
                <td class="alignRight">
                    <span title="AttributeMetadataId" style="color:#296E8E">@Html.Encode(meta.Id)</span>
                </td>
                <td>
                    @Html.Encode(meta.Attribute.Value)
                </td>
                <td style="text-align:right">
                    @Html.Encode(Dogwood.Service.AttributeMetadataService.GetDataType((Dogwood.Core.DogwoodDataType)meta.DataTypeId))
                </td>
                <td style="text-align:right">
                    @Html.Encode(meta.IsNullable)
                </td>
                <td style="text-align:right">
                    @Html.Encode(meta.IsImmutable)
                </td>
            </tr>
        }

        foreach (var meta in item.RelationshipMetadataAsFk)
        {

            <tr>
                <td>
                    &nbsp;
                </td>
                <td class="alignRight">
                   <span title="RelationMetadataId" style="color:#84A530">@Html.Encode(meta.Id)</span> 
                </td>
                <td>
                    @Html.Encode(meta.Attribute.Value)
                </td>
                <td  colspan="3">&nbsp;</td>
            </tr>
            
        }

    }
</table>
@section cphHeadContent
{
    <style type="text/css">
        .classRow
        {
            font-weight: bold;
            color: #CC0000;
            font-style: italic;
        }
        
        .metaRow
        {
            margin-left: 20px;
        }
        
        .relationRow
        {
            margin-left: 20px;
            color: #00CC00;
        }
    </style>
}

Source/Dogwood.Web.Mvc/Views/Class/Delete.cshtml
@model Dogwood.Web.Mvc.Models.Class.DeleteViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cphHeadContent {
}
<h1>
    Edit Bool Attribute</h1>
@using (Html.BeginForm())
{       
    <table>
        <tr>
            <td>
                Id:
            </td>
            <td>@Html.Encode(Model.Id)
            </td>
        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Html.Encode(Model.Name)
            </td>
        </tr>
    </table>
    @Html.HiddenFor(m => m.Id)  
    @Html.ActionLink("Cancel", "Details", new { id = Model.Id })       
    <input type="submit" value="Delete" />
}

Source/Dogwood.Web.Mvc/Views/Class/Details.cshtml
@model Dogwood.Web.Mvc.Models.Class.DetailsViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cphHeadContent{
    <style type="text/css">
        .attRow
        {
            background-color: #efefef;
        }
    </style>
    <link href="/Content/Fancybox/jquery.fancybox-1.3.1.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/Scripts/jquery.fancybox-1.3.1.pack.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            Init_iframe();
        });

        function Init_iframe() {
            $(".iframe").fancybox({
                'height': 600,
                'width': 1500,
                'onClosed': function () {
                    $.ajax({
                        type: "GET",
                        cache: false,
                        url: "/Class/DetailsTable/@Model.Id",
                        success: function (data) {
                            $("#detailsTable").html(data);
                            Init_iframe();
                        }
                    });
                }
            });
        }
    </script>
}
<div id="detailsTable">
    @Html.Partial("DetailsTable", Model)
</div>

Source/Dogwood.Web.Mvc/Views/Class/DetailsTable.cshtml
@model Dogwood.Web.Mvc.Models.Class.DetailsViewModel
<h1>
    @Model.Class.Name Details</h1>
<a href="/Class/Index">Back</a><br />
@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "iframe" })<br />
@Html.ActionLink("Entity View", "Entity", new { id = Model.Id }, new { @class = "iframe" })<br />
@Html.ActionLink("Create New Object", "CreateObjectSql", new { Model.Id }, new { @class = "iframe" })
<table>
    <tr>
        <td colspan="5" class="attRow">
            Attributes
        </td>
        <td>@Html.ActionLink("Create", "Create", "AttributeMeta", new { id = Model.Id }, new { @class = "iframe" })
        </td>
        <td>
            Sql
        </td>
    </tr>
    @foreach (var item in Model.Class.AttributeMetadata)
    {
        <tr>
            <td colspan="3">
                @Html.Encode(item.Attribute.Value)
            </td>
            <td>
                @Html.Encode(Dogwood.Service.AttributeMetadataService.GetDataType((Dogwood.Core.DogwoodDataType)item.DataTypeId))
            </td>
            <td>
                @Html.Encode(item.IsNullable)
            </td>
            <td>@Html.ActionLink("Edit", "Edit", "AttributeMeta", new { id = item.Id }, new { @class = "iframe" })
            </td>
            <td>
                @Html.ActionLink("Create Sql", "CreateSql", "AttributeMeta", new { item.Id }, new { @class = "iframe" })
            </td>
        </tr>
    }
    <tr>
        <td colspan="5" class="attRow">
            Relationship Attributes as Foreign Key
        </td>
        <td>@Html.ActionLink("Create", "Create", "RelationshipMeta", new { id = Model.Id }, new { @class = "iframe" })
        </td>
        <td>
            Sql
        </td>
    </tr>
    @foreach (var item in Model.Class.RelationshipMetadataAsFk)
    {
        <tr>
            <td>
                @Html.Encode(item.Attribute.Value)
            </td>
            <td>
                @Html.Encode(item.PkClass.Name)
            </td>
            <td>
                @Html.Encode(item.OneToManyValue)
            </td>
            <td>
                @Html.Encode(item.IsNullable)
            </td>
            <td>
                @if (item.CascadeBehavior == 1)
                {
                    <text>Delete</text>
                }
                else if (item.CascadeBehavior == 2)
                {
                    <text>Set to Null</text>
                }
                else if (item.CascadeBehavior == 3)
                {
                    <text>Set to default value: @item.CascadeDefaultValue</text>
                }
            </td>
            <td>@Html.ActionLink("Edit", "Edit", "RelationshipMeta", new { id = item.Id }, new { @class = "iframe" })
            </td>
            <td>
                @Html.ActionLink("Create Sql", "CreateSql", "RelationshipMeta", new { item.Id }, new { @class = "iframe" })
            </td>
        </tr>

    }
    <tr>
        <td colspan="5" class="attRow">
            Relationship Attributes As Primary Key
        </td>
        <td>
            &nbsp;
        </td>
        <td>
            &nbsp;
        </td>
    </tr>
    @foreach (var item in Model.Class.RelationshipMetadataAsPk)
    {
        <tr>
            <td>
                @Html.Encode(item.Attribute.Value)
            </td>
            <td>
                @Html.Encode(item.FkClass.Name)
            </td>
            <td>
                @Html.Encode(item.OneToManyValue)
            </td>
            <td>
                @Html.Encode(item.IsNullable)
            </td>
            <td>
                @if (item.CascadeBehavior == 1)
                {
                    <text>Delete</text>
                }
                else if (item.CascadeBehavior == 2)
                {
                    <text>Set to Null</text>
                }
                else if (item.CascadeBehavior == 3)
                {
                    <text>Set to default value: @item.CascadeDefaultValue</text>
                }
            </td>
            <td>@Html.ActionLink("Edit", "Edit", "RelationshipMeta", new { id = item.Id }, new { @class = "iframe" })
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
    }
</table>

Source/Dogwood.Web.Mvc/Views/Class/Edit.cshtml
@model Dogwood.Web.Mvc.Models.Class.EditViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cphHeadContent {
}
<h1>
    Edit Class</h1>
@Html.ValidationSummary()
@using (Html.BeginForm())
{       
    <table>
        <tr>
            <td>
                Name:
            </td>
            <td>
                @Html.TextBoxFor(m => m.Name)
            </td>
        </tr>
    </table> 
    <a class="cancel button" href="javascript:if(parent.$.fancybox){parent.$.fancybox.close();}">
        Cancel</a>   
    @Html.ActionLink("Delete", "Delete", new { id = @Model.Id }, new { target = "_parent", @class = "delete button" }) 
    @Html.HiddenFor(m => m.Id);
    <input type="submit" value="Save" class="save button" />
}

Source/Dogwood.Web.Mvc/Views/Class/Entity.cshtml
@model Dogwood.Web.Mvc.Models.Class.EntityViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("EntityCode", Model)