Source/Dogwood.Web.Mvc/Models/Class/DetailsViewModel.cs
using Dogwood.Data.EntityClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.DatabaseSpecific;
using Dogwood.Data;

namespace Dogwood.Web.Mvc.Models.Class
{
    public class DetailsViewModel
    {
        public int Id { get; set; }
        public ClassEntity Class { get; set; }

        public DetailsViewModel(int id)
        {
            Id = id;

            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                Class = new ClassEntity(id);

                IPrefetchPath2 prefetchPath = new PrefetchPath2(EntityType.ClassEntity);
                
                prefetchPath.Add(ClassEntity.PrefetchPathAttributeMetadata).SubPath.Add(AttributeMetadataEntity.PrefetchPathAttribute);

                var fkelement = prefetchPath.Add(ClassEntity.PrefetchPathRelationshipMetadataAsFk);
                fkelement.SubPath.Add(RelationshipMetadataEntity.PrefetchPathAttribute);
                fkelement.SubPath.Add(RelationshipMetadataEntity.PrefetchPathPkClass);

                var pkelement = prefetchPath.Add(ClassEntity.PrefetchPathRelationshipMetadataAsPk);
                pkelement.SubPath.Add(RelationshipMetadataEntity.PrefetchPathAttribute);
                pkelement.SubPath.Add(RelationshipMetadataEntity.PrefetchPathFkClass);
                
                prefetchPath.Add(ClassEntity.PrefetchPathObject);

                adapter.FetchEntity(Class, prefetchPath);
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Models/Object/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Dogwood.Data.EntityClasses;
using Dogwood.Data.DatabaseSpecific;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.HelperClasses;
using Dogwood.Data;

namespace Dogwood.Web.Mvc.Models.Object
{
    public class DetailsViewModel
    {
        public ObjectEntity Obj { get; set; }

        public DetailsViewModel(int id)
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                IPrefetchPath2 path = new PrefetchPath2(EntityType.ObjectEntity);
                
                IPrefetchPathElement2 objRevElement = path.Add(ObjectEntity.PrefetchPathObjectRevision);
                    objRevElement.SubPath.Add(ObjectRevisionEntity.PrefetchPathRevision);
                    objRevElement.SubPath.Add(ObjectRevisionEntity.PrefetchPathAttributeValue);
                    objRevElement.SubPath.Add(ObjectRevisionEntity.PrefetchPathRelationAttributeValue);

                IPrefetchPathElement2 classElement = path.Add(ObjectEntity.PrefetchPathClass);
                    classElement.SubPath.Add(ClassEntity.PrefetchPathRelationshipMetadataAsFk).SubPath.Add(RelationshipMetadataEntity.PrefetchPathAttribute);                    
                    classElement.SubPath.Add(ClassEntity.PrefetchPathAttributeMetadata).SubPath.Add(AttributeMetadataEntity.PrefetchPathAttribute);

                this.Obj = new ObjectEntity(id);
                adapter.FetchEntity(this.Obj, path);
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Models/Revision/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Dogwood.Data.EntityClasses;
using Dogwood.Data.DatabaseSpecific;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data;
using Dogwood.Data.HelperClasses;

namespace Dogwood.Web.Mvc.Models.Revision
{
    public class DetailsViewModel
    {
        public int RevisionId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? CreatedById { get; set; }
        public string Tag { get; set; }
        public IList<ObjectRevisionEntity> RevisedObjects { get; set; }
        public int? PreviousRevisionInBranch { get; set; }
        public int? NextRevisionInBranch { get; set; }

        // branches into...

        public DetailsViewModel(int id)
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                IPrefetchPath2 prefetchPath = new PrefetchPath2(EntityType.RevisionEntity);
                prefetchPath.Add(RevisionEntity.PrefetchPathObjectRevision);                    
                RevisionEntity revision = new RevisionEntity(id);
                adapter.FetchEntity(revision, prefetchPath);

                EntityCollection<RevisionEntity> branchRevisions = new EntityCollection<RevisionEntity>();
                IRelationPredicateBucket filterBucket = new RelationPredicateBucket();
                filterBucket.PredicateExpression.Add(RevisionFields.BranchId == revision.BranchId);
                adapter.FetchEntityCollection(branchRevisions, filterBucket);

                this.RevisionId = id;
                this.CreatedDate = revision.TimeStamp;
                this.CreatedById = revision.CreatedBy;
                this.Tag = revision.Tag;
                this.RevisedObjects = revision.ObjectRevision.ToList();

                for (int i = 0; i < branchRevisions.Count; i++)
                {
                    if (branchRevisions[i].Id == id)
                    {
                        if (i > 0)
                        {
                            this.PreviousRevisionInBranch = branchRevisions[i - 1].Id;
                        }

                        if (i < branchRevisions.Count - 1)
                        {
                            this.NextRevisionInBranch = branchRevisions[i+1].Id;
                        }
                    }
                }
            }
        }
    }
}

Source/Dogwood.Web.Mvc/Models/Revision/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Dogwood.Data.EntityClasses;
using Dogwood.Data.DatabaseSpecific;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Dogwood.Data.HelperClasses;

namespace Dogwood.Web.Mvc.Models.Revision
{
    public class IndexViewModel
    {
        private IList<RevisionEntity> AllRevisions { get; set; }
        public IList<Revision> RevisionTree { get; set; }

        public IndexViewModel()
        {
            using (IDataAccessAdapter adapter = new DataAccessAdapter(true))
            {
                EntityCollection<RevisionEntity> allRevisions = new EntityCollection<RevisionEntity>();
                adapter.FetchEntityCollection(allRevisions, null);
                this.AllRevisions = allRevisions.OrderBy(m=>m.Id).ToList();

                RevisionTree = new List<Revision>();

                foreach (var item in this.AllRevisions.Where(m=>m.Id == 0))
                {
                    Revision toAdd = new Revision();
                    toAdd.Item = item;
                    AddChildren(toAdd);
                    RevisionTree.Add(toAdd);
                }
            }
        }

        private void AddChildren(Revision item)
        {
            foreach (var child in AllRevisions.Where(m=>m.BranchId == item.Item.Id && m.Id != 0))
            {
                Revision toAdd = new Revision();
                toAdd.Item = child;
                
                AddChildren(toAdd);

                if (item.Children == null)
                {
                    item.Children = new List<Revision>();
                }
                
                item.Children.Add(toAdd);
            }
        }
    }

    public class Revision
    {
        public RevisionEntity Item { get; set; }
        public IList<Revision> Children { get; set; }
    }
}

Source/Dogwood.Web.Mvc/Controllers/ObjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dogwood.Web.Mvc.Models.Object;

namespace Dogwood.Web.Mvc.Controllers
{
    public class ObjectController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            IndexViewModel vm = new IndexViewModel();
            return View(vm);
        }

        public ActionResult Type(int id)
        {
            TypeViewModel vm = new TypeViewModel(id);
            return View(vm);
        }

        public ActionResult Details(int id)
        {
            DetailsViewModel vm = new DetailsViewModel(id);
            return View(vm);
        }

        public ActionResult ObjectRevision(int id)
        {
            ObjectRevisionViewModel vm = new ObjectRevisionViewModel(id);
            return View(vm);
        }
    }
}

Source/Dogwood.Web.Mvc/Controllers/RevisionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dogwood.Web.Mvc.Models.Revision;

namespace Dogwood.Web.Mvc.Controllers
{
    public class RevisionController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            IndexViewModel vm = new IndexViewModel();
            return View(vm);
        }
        public ActionResult Details(int id)
        {
            DetailsViewModel vm = new DetailsViewModel(id);
            return View(vm);
        }

    }
}

Source/Dogwood.Web.Mvc/Views/Revision/Details.cshtml
@model Dogwood.Web.Mvc.Models.Revision.DetailsViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cphHeadContent {
}
<h1>
    Revision Details</h1>
<table>
    <tr>
        <td>
            Revision Id
        </td>
        <td>@Model.RevisionId
        </td>
    </tr>
    <tr>
        <td>
            Created Date
        </td>
        <td>@Model.CreatedDate
        </td>
    </tr>
    <tr>
        <td>
            Created By
        </td>
        <td>@Model.CreatedById
        </td>
    </tr>
    <tr>
        <td>
            Previous Revision In Branch
        </td>
        <td>
            @if (Model.PreviousRevisionInBranch != null)
            {
                @Html.ActionLink(Model.PreviousRevisionInBranch.ToString(), "Details", new { id = Model.PreviousRevisionInBranch })
            }
        </td>
    </tr>
    <tr>
        <td>
            Next Revision In Branch
        </td>
        <td>
            @if (Model.NextRevisionInBranch != null)
            {
                @Html.ActionLink(Model.NextRevisionInBranch.ToString(), "Details", new { id = Model.NextRevisionInBranch })    
            }
        </td>
    </tr>
</table>
<h2>@Model.RevisedObjects.Count Objects Revised</h2>
<ul>
    @foreach (var obj in Model.RevisedObjects)
    {
        <li>@Html.ActionLink(obj.ObjectId.ToString(), "Details", "Object", new { id = obj.ObjectId}, new {target="_parent" })</li>
    }
</ul>

Source/Dogwood.Web.Mvc/Views/Revision/Index.cshtml
@model Dogwood.Web.Mvc.Models.Revision.IndexViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section cphHeadContent {
    <link href="/Content/Fancybox/jquery.fancybox-1.3.1.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="../../Scripts/jquery.fancybox-1.3.1.pack.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            Init_iframe();
        });

        function Init_iframe() {
            $(".iframe").fancybox({
                'height': 350,
                'width': 600                
            });
        }
    </script>
}
<h1>
    Revision Tree</h1>
    <a href="/">Home</a>
<div id="attributeList">
    <ul>
        @foreach (var item in Model.RevisionTree)
        {
            <li>@item.Item.Id</li>
            @Html.Partial("RevisionTree", item)
        }
    </ul>
</div>

Source/Dogwood.Web.Mvc/Views/Revision/RevisionTree.cshtml
@model Dogwood.Web.Mvc.Models.Revision.Revision
@if (Model.Children != null)
{   
    <ul id="@(string.Format("list_{0}", Model.Item.Id))">
        @foreach (var item in Model.Children)
        {
            <li>
                @if (item.Children != null)
                {
                    <a href="javascript:void(0)" onclick="$('#@(string.Format("list_{0}", item.Item.Id)) li:visible').hide()">
                        -</a><a href="javascript:void(0)" onclick="$('#@(string.Format("list_{0}", item.Item.Id)) li:hidden').show()">+</a>
                }
                @Html.ActionLink(string.Format("{0}{1}", item.Item.Id, !string.IsNullOrEmpty(item.Item.Tag) ? string.Format(" - {0}", item.Item.Tag) : ""), "Details", new { id = item.Item.Id }, new { @class = "iframe" })
            </li>
            @Html.Partial("RevisionTree", item)
        }
    </ul>
}